export const costStaticRoutes = {
  isDel: false,
  createId: 1,
  createDate: "2025-12-23 16:41:38",
  operId: 1,
  operDate: "2025-12-23 16:41:38",
  id: 9898,
  pid: 0,
  name: "cost-management",
  title: "成本管理",
  icon: "Monitor",
  menuType: 0,
  component: "",
  path: "",
  isKeepAlive: false,
  isControl: true,
  isVisible: true,
  sort: 4,
  children: [
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 151,
      operDate: "2026-04-23 10:07:32",
      id: 151,
      pid: 9898,
      name: "master-data",
      title: "主数据",
      icon: "Document",
      menuType: 1,
      component: "master-data",
      path: "master-data",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 1,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161,
          pid: 151,
          name: "dictionary",
          title: "数据字典",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/dictionary/index",
          path: "master-data/dictionary",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 1,
        },
        {
          isDel: false,
          createId: 3,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 163,
          pid: 151,
          name: "contract-category",
          title: "合同类别",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/contract-category/index",
          path: "master-data/contract-category",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 2,
        },
        {
          isDel: false,
          createId: 3,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1654,
          pid: 151,
          name: "supplier-category",
          title: "供应商类别",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/supplier-category/index",
          path: "master-data/supplier-category",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 3,
        },
        {
          isDel: false,
          createId: 2,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 162,
          pid: 151,
          name: "project-area",
          title: "项目面积",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/project-area/index",
          path: "master-data/project-area",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 4,
        },
        {
          isDel: false,
          createId: 2,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 162,
          pid: 151,
          name: "product-type",
          title: "产品类型",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/product-type/index",
          path: "master-data/product-type",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 5,
        },
        {
          isDel: false,
          createId: 2,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 163,
          pid: 151,
          name: "cost-category",
          title: "成本科目",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/cost-category/index",
          path: "master-data/cost-category",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 6,
        },
        {
          isDel: false,
          createId: 2,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 164,
          pid: 151,
          name: "management-unit",
          title: "分部查询",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/management-unit/index",
          path: "master-data/management-unit",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 7,
        },
      ],
    },
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 152,
      operDate: "2026-04-23 10:07:32",
      id: 152,
      pid: 9898,
      name: "supplier",
      title: "供应商",
      icon: "Document",
      menuType: 1,
      component: "supplier",
      path: "supplier",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 2,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 16111,
          pid: 152,
          name: "supplier-ledger",
          title: "供应商台账",
          icon: "Edit",
          menuType: 1,
          component: "cost/supplier/supplier-ledger/index",
          path: "supplier/supplier-ledger",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 1,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 16222,
          pid: 152,
          name: "supplier-register-add",
          title: "供应商登记",
          icon: "Edit",
          menuType: 1,
          component: "cost/supplier/supplier-register/index",
          path: "supplier/supplier-register/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 2,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 16223,
          pid: 152,
          name: "supplier-register-edit",
          title: "供应商编辑",
          icon: "Edit",
          menuType: 1,
          component: "cost/supplier/supplier-register/index",
          path: "supplier/supplier-register/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 3,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1623423,
          pid: 152,
          name: "supplier-register-detail",
          title: "供应商台账详情",
          icon: "Edit",
          menuType: 1,
          component: "cost/supplier/supplier-register/index",
          path: "supplier/supplier-register/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 3,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1623442323,
          pid: 152,
          name: "supplier-inspection-add",
          title: "供应商入库审批",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/supplier/supplier-inspection/supplier-inspection-add",
          path: "supplier/inspection/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 3,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1624323423,
          pid: 152,
          name: "supplier-inspection-edit",
          title: "供应商入库编辑",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/supplier/supplier-inspection/supplier-inspection-edit",
          path: "supplier/inspection/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 3,
        },
      ],
    },
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 153,
      operDate: "2026-04-23 10:07:32",
      id: 153,
      pid: 9898,
      name: "cost-setting",
      title: "目标成本",
      icon: "Document",
      menuType: 1,
      component: "cost-setting",
      path: "cost-setting",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 3,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161112,
          pid: 153,
          name: "goal-cost",
          title: "目标成本编制",
          icon: "Edit",
          menuType: 1,
          component: "cost/cost-setting/goal-cost/index",
          path: "cost/goal-cost",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 2,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161113,
          pid: 153,
          name: "cost-detail",
          title: "目标成本明细",
          icon: "Edit",
          menuType: 1,
          component: "cost/cost-setting/goal-cost/components/cost-detail/index",
          path: "cost/cost-detail",
          isKeepAlive: false,
          isControl: true,
          isVisible: false,
          sort: 3,
        },
      ],
    },
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 153,
      operDate: "2026-04-23 10:07:32",
      id: 154,
      pid: 9898,
      name: "bidding",
      title: "招标管理",
      icon: "Document",
      menuType: 1,
      component: "bidding",
      path: "bidding",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 4,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1611445,
          pid: 154,
          name: "bidding-demand",
          title: "招标需求",
          icon: "Edit",
          menuType: 1,
          component: "cost/bidding/bidding-demand/index",
          path: "bidding/bidding-demand",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 1,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1611321445,
          pid: 154,
          name: "bidding-demand-add",
          title: "新增招标需求",
          icon: "Edit",
          menuType: 1,
          component: "cost/bidding/bidding-demand/bidding-demand-add",
          path: "bidding/bidding-demand/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 1,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 16113214245,
          pid: 154,
          name: "bidding-demand-edit",
          title: "编辑招标需求",
          icon: "Edit",
          menuType: 1,
          component: "cost/bidding/bidding-demand/bidding-demand-edit",
          path: "bidding/bidding-demand/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 1,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 163214245,
          pid: 154,
          name: "bidding-demand-detail",
          title: "招标需求详情",
          icon: "Edit",
          menuType: 1,
          component: "cost/bidding/bidding-demand/bidding-demand-detail",
          path: "bidding/bidding-demand/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 1,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 16112,
          pid: 154,
          name: "tender-matter",
          title: "招标事项",
          icon: "Edit",
          menuType: 1,
          component: "cost/bidding/tender-matter/index",
          path: "bidding/tender-matter",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 2,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 16113,
          pid: 154,
          name: "bidding-detail",
          title: "招标详情",
          icon: "Edit",
          menuType: 1,
          component: "cost/bidding/tender-matter/bidding-detail",
          path: "bidding/bidding-detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 3,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161144,
          pid: 154,
          name: "tender-plan-add",
          title: "新增招标计划",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/tender-plan/tender-plan-add",
          path: "bidding/tender-plan/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 4,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161145,
          pid: 154,
          name: "tender-plan-edit",
          title: "编辑招标计划",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/tender-plan/tender-plan-edit",
          path: "bidding/tender-plan/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 5,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161146,
          pid: 154,
          name: "tender-plan-detail",
          title: "招标计划详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/tender-plan/tender-plan-detail",
          path: "bidding/tender-plan/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 6,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161147,
          pid: 154,
          name: "reference-price-add",
          title: "新增定标参考价",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/reference-price/reference-price-add",
          path: "bidding/reference-price/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 6,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161148,
          pid: 154,
          name: "reference-price-edit",
          title: "编辑定标参考价",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/reference-price/reference-price-edit",
          path: "bidding/reference-price/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 7,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161149,
          pid: 154,
          name: "reference-price-detail",
          title: "定标参考价详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/reference-price/reference-price-detail",
          path: "bidding/reference-price/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 8,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161150,
          pid: 154,
          name: "award-approval-add",
          title: "新增定标审批",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/award-approval/award-approval-add",
          path: "bidding/award-approval/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 9,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161151,
          pid: 154,
          name: "award-approval-edit",
          title: "编辑定标审批",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/award-approval/award-approval-edit",
          path: "bidding/award-approval/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 10,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161152,
          pid: 154,
          name: "award-approval-detail",
          title: "定标审批详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/award-approval/award-approval-detail",
          path: "bidding/award-approval/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 11,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161153,
          pid: 154,
          name: "bid-bond-pay-add",
          title: "新增保证金缴纳",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-pay/bid-bond-pay-add",
          path: "bidding/bid-bond-pay/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 12,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161154,
          pid: 154,
          name: "bid-bond-pay-edit",
          title: "编辑保证金缴纳",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-pay/bid-bond-pay-edit",
          path: "bidding/bid-bond-pay/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 13,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161155,
          pid: 154,
          name: "bid-bond-pay-detail",
          title: "保证金缴纳详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-pay/bid-bond-pay-detail",
          path: "bidding/bid-bond-pay/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 14,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161156,
          pid: 154,
          name: "bid-bond-refund-add",
          title: "新增保证金退还",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-refund/bid-bond-refund-add",
          path: "bidding/bid-bond-refund/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 15,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161157,
          pid: 154,
          name: "bid-bond-refund-edit",
          title: "编辑保证金退还",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-refund/bid-bond-refund-edit",
          path: "bidding/bid-bond-refund/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 16,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161158,
          pid: 154,
          name: "bid-bond-refund-detail",
          title: "保证金退还详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-refund/bid-bond-refund-detail",
          path: "bidding/bid-bond-refund/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 17,
        },
      ],
    },
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 153,
      operDate: "2026-04-23 10:07:32",
      id: 1541,
      pid: 9899,
      name: "contract-manage",
      title: "合同管理",
      icon: "Document",
      menuType: 1,
      component: "contract-manage",
      path: "contract-manage",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 5,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13541,
          pid: 1540,
          name: "contract-ledger",
          title: "合同台账",
          icon: "Edit",
          menuType: 1,
          component: "cost/contract-manage/contract-ledger/index",
          path: "con/contract-ledger",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 1,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13542,
          pid: 1540,
          name: "contract-ledger-add",
          title: "录入合同",
          icon: "Edit",
          menuType: 1,
          component: "cost/contract-manage/contract-ledger/contract-ledger-add",
          path: "con/contract-ledger/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          // isMultiOpen: true,
          sort: 2,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13543,
          pid: 1540,
          name: "contract-ledger-edit",
          title: "编辑合同",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/contract-ledger-edit",
          path: "con/contract-ledger/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          // isMultiOpen: true,
          sort: 3,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13544,
          pid: 1540,
          name: "contract-ledger-detail",
          title: "合同台账详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/contract-ledger-detail",
          path: "con/contract-ledger/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 4,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13545,
          pid: 1540,
          name: "supplement-contract-add",
          title: "新增补充合同",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/supplement-contract/supplement-contract-add",
          path: "con/supplement-contract/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 5,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13546,
          pid: 1540,
          name: "supplement-contract-edit",
          title: "编辑补充合同",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/supplement-contract/supplement-contract-edit",
          path: "con/supplement-contract/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 6,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13546,
          pid: 1540,
          name: "supplement-contract-detail",
          title: "补充合同详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/supplement-contract/supplement-contract-detail",
          path: "con/supplement-contract/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 6,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13547,
          pid: 1540,
          name: "change-order-add",
          title: "新增变更",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/change-order/change-order-add",
          path: "con/change-order/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 7,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13549,
          pid: 1540,
          name: "change-order-edit",
          title: "编辑变更",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/change-order/change-order-edit",
          path: "con/change-order/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 7,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13546,
          pid: 1540,
          name: "change-order-detail",
          title: "变更详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/change-order/change-order-detail",
          path: "con/change-order/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 7,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13546,
          pid: 1540,
          name: "visa-management-add",
          title: "新增签证",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/visa-manage/visa-manage-add",
          path: "con/visa-manage/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 7,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13546,
          pid: 1540,
          name: "visa-management-edit",
          title: "编辑签证",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/visa-manage/visa-manage-edit",
          path: "con/visa-manage/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 7,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13546,
          pid: 1540,
          name: "visa-management-detail",
          title: "签证详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/visa-manage/visa-manage-detail",
          path: "con/visa-manage/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 7,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13547,
          pid: 1540,
          name: "output-declaration-add",
          title: "新增产值申报",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/output-declaration/output-declaration-add",
          path: "con/output-declaration/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 7,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13548,
          pid: 1540,
          name: "output-declaration-edit",
          title: "编辑产值申报",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/output-declaration/output-declaration-edit",
          path: "con/output-declaration/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 8,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 135434243,
          pid: 1540,
          name: "payment-adjust-add",
          title: "新增款项调整",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/payment-adjust/payment-adjust-add",
          path: "con/payment-adjust/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 8,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 136454243,
          pid: 1540,
          name: "payment-adjust-edit",
          title: "编辑款项调整",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/payment-adjust/payment-adjust-edit",
          path: "con/payment-adjust/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 8,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 136498743,
          pid: 1540,
          name: "special-matter-add",
          title: "新增特殊事项",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/special-matter/special-matter-add",
          path: "con/special-matter/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 8,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 136498743,
          pid: 1540,
          name: "special-matter-edit",
          title: "编辑特殊事项",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/special-matter/special-matter-edit",
          path: "con/special-matter/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 8,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 136498743,
          pid: 1540,
          name: "engineering-price-add",
          title: "新增工程核价",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/engineering-price/engineering-price-add",
          path: "con/engineering-price/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 8,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13643215443,
          pid: 1540,
          name: "engineering-price-edit",
          title: "编辑工程核价",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/engineering-price/engineering-price-edit",
          path: "con/engineering-price/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 8,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13549,
          pid: 1540,
          name: "contract-settle-add",
          title: "新增合同结算",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/contract-settle/contract-settle-add",
          path: "con/contract-settle/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 9,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13550,
          pid: 1540,
          name: "contract-settle-edit",
          title: "编辑合同结算",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/contract-settle/contract-settle-edit",
          path: "con/contract-settle/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 10,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13550,
          pid: 1540,
          name: "payment-application-add",
          title: "新增付款申请",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/payment-application/payment-application-add",
          path: "con/payment-application/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 10,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13551,
          pid: 1540,
          name: "payment-application-edit",
          title: "编辑付款申请",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/payment-application/payment-application-edit",
          path: "con/payment-application/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 11,
        },
        // {
        //   isDel: false,
        //   createId: 1,
        //   createDate: "2025-12-24 10:02:05",
        //   operId: 1,
        //   operDate: "2025-12-24 10:02:05",
        //   id: 13552,
        //   pid: 1540,
        //   name: "payment-application-detail",
        //   title: "付款申请详情",
        //   icon: "Edit",
        //   menuType: 1,
        //   component:
        //     "cost/contract-manage/contract-ledger/payment-application/payment-application-detail",
        //   path: "con/payment-application/detail",
        //   isKeepAlive: true,
        //   isControl: true,
        //   isVisible: false,
        //   sort: 12,
        // },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 6546,
          pid: 1540,
          name: "contract-void-add",
          title: "新增合同解除",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/contract-void/contract-void-add",
          path: "con/contract-void/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 12,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 3215456165465546132,
          pid: 1540,
          name: "contract-void-edit",
          title: "编辑合同解除",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/contract-manage/contract-ledger/contract-void/contract-void-edit",
          path: "con/contract-void/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 12,
        },
      ],
    },
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 153,
      operDate: "2026-04-23 10:07:32",
      id: 1542,
      pid: 9899,
      name: "non-contract-manage",
      title: "非合同管理",
      icon: "Document",
      menuType: 1,
      component: "non-contract-manage",
      path: "non-contract-manage",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 6,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 135421,
          pid: 1542,
          name: "cst-process",
          title: "非合同立项",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/cst-process/index",
          path: "ncon/cst-process",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 1,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1325421,
          pid: 1542,
          name: "cst-process-add",
          title: "新增建安立项",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/cst-process/cst-process-add",
          path: "ncon/cst-process/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 2,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1326421,
          pid: 1542,
          name: "cst-process-edit",
          title: "编辑建安立项",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/cst-process/cst-process-edit",
          path: "ncon/cst-process/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 3,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1326421,
          pid: 1542,
          name: "cst-process-detail",
          title: "建安立项详情",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/cst-process/cst-process-detail",
          path: "ncon/cst-process/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 4,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 135422,
          pid: 1542,
          name: "cst-payment",
          title: "非合同请款",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/cst-payment/index",
          path: "ncon/cst-payment",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 5,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 135423,
          pid: 1542,
          name: "cst-payment-add",
          title: "新增非合同请款",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/cst-payment/cst-payment-add",
          path: "ncon/cst-payment/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 6,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 135424,
          pid: 1542,
          name: "cst-payment-edit",
          title: "编辑非合同请款",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/cst-payment/cst-payment-edit",
          path: "ncon/cst-payment/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 7,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 135425,
          pid: 1542,
          name: "cst-payment-detail",
          title: "非合同请款详情",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/cst-payment/cst-payment-detail",
          path: "ncon/cst-payment/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 8,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 135426,
          pid: 1542,
          name: "fee-payment",
          title: "费用报销",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/fee-payment/index",
          path: "ncon/fee-payment",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 9,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 135427,
          pid: 1542,
          name: "fee-payment-add",
          title: "新增费用报销",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/fee-payment/fee-payment-add",
          path: "ncon/fee-payment/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 10,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 135427,
          pid: 1542,
          name: "fee-payment-edit",
          title: "编辑费用报销",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/fee-payment/fee-payment-edit",
          path: "ncon/fee-payment/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 11,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 135427,
          pid: 1542,
          name: "fee-payment-detail",
          title: "费用报销详情",
          icon: "Edit",
          menuType: 1,
          component: "cost/non-contract-manage/fee-payment/fee-payment-detail",
          path: "ncon/fee-payment/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 12,
        },
      ],
    },
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 153,
      operDate: "2026-04-23 10:07:32",
      id: 1543,
      pid: 9899,
      name: "payment-manage",
      title: "付款管理",
      icon: "Document",
      menuType: 1,
      component: "payment-manage",
      path: "payment-manage",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 7,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1354321,
          pid: 1542,
          name: "invoice-manage",
          title: "发票管理",
          icon: "Edit",
          menuType: 1,
          component: "cost/payment-manage/invoice-manage/index",
          path: "payment/invoice-manage",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 1,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1354322,
          pid: 1542,
          name: "payment-register",
          title: "实付登记",
          icon: "Edit",
          menuType: 1,
          component: "cost/payment-manage/payment-register/index",
          path: "payment/payment-register",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 2,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1354323,
          pid: 1542,
          name: "payment-apply",
          title: "合同请款",
          icon: "Edit",
          menuType: 1,
          component: "cost/payment-manage/payment-apply/index",
          path: "payment/payment-apply",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 3,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1354323,
          pid: 1542,
          name: "payment-apply-add",
          title: "新增付款申请",
          icon: "Edit",
          menuType: 1,
          component: "cost/payment-manage/payment-apply/payment-apply-add",
          path: "payment/payment-apply/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 4,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1354323,
          pid: 1542,
          name: "payment-apply-edit",
          title: "编辑付款申请",
          icon: "Edit",
          menuType: 1,
          component: "cost/payment-manage/payment-apply/payment-apply-edit",
          path: "payment/payment-apply/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 5,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1354323,
          pid: 1542,
          name: "payment-apply-detail",
          title: "付款申请详情",
          icon: "Edit",
          menuType: 1,
          component: "cost/payment-manage/payment-apply/payment-apply-detail",
          path: "payment/payment-apply/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 6,
        },
      ],
    },
  ],
};
