export const costStaticRoutes = {
  isDel: false,
  createId: 1,
  createDate: "2025-12-23 16:41:38",
  operId: 1,
  operDate: "2025-12-23 16:41:38",
  id: 9898,
  pid: 0,
  name: "cost-management",
  title: "成本管理",
  icon: "Monitor",
  menuType: 0,
  component: "",
  path: "",
  isKeepAlive: false,
  isControl: true,
  isVisible: true,
  sort: 4,
  children: [
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 151,
      operDate: "2026-04-23 10:07:32",
      id: 151,
      pid: 9898,
      name: "master-data",
      title: "主数据",
      icon: "Document",
      menuType: 1,
      component: "master-data",
      path: "master-data",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 1,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161,
          pid: 151,
          name: "dictionary",
          title: "数据字典",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/dictionary/index",
          path: "master-data/dictionary",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 1,
        },
        {
          isDel: false,
          createId: 3,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 163,
          pid: 151,
          name: "contract-category",
          title: "合同类别",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/contract-category/index",
          path: "master-data/contract-category",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 2,
        },
        {
          isDel: false,
          createId: 3,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1654,
          pid: 151,
          name: "supplier-category",
          title: "供应商类别",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/supplier-category/index",
          path: "master-data/supplier-category",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 3,
        },
        {
          isDel: false,
          createId: 2,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 162,
          pid: 151,
          name: "project-area",
          title: "项目面积",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/project-area/index",
          path: "master-data/project-area",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 4,
        },
        {
          isDel: false,
          createId: 2,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 162,
          pid: 151,
          name: "product-type",
          title: "产品类型",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/product-type/index",
          path: "master-data/product-type",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 5,
        },
        {
          isDel: false,
          createId: 2,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 163,
          pid: 151,
          name: "cost-category",
          title: "成本科目",
          icon: "Edit",
          menuType: 1,
          component: "cost/master-data/cost-category/index",
          path: "master-data/cost-category",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 6,
        },
      ],
    },
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 152,
      operDate: "2026-04-23 10:07:32",
      id: 152,
      pid: 9898,
      name: "supplier",
      title: "供应商",
      icon: "Document",
      menuType: 1,
      component: "supplier",
      path: "supplier",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 2,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 16111,
          pid: 152,
          name: "supplier-ledger",
          title: "供应商台账",
          icon: "Edit",
          menuType: 1,
          component: "cost/supplier/supplier-ledger/index",
          path: "supplier/supplier-ledger",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 1,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 16222,
          pid: 152,
          name: "supplier-register",
          title: "供应商登记",
          icon: "Edit",
          menuType: 1,
          component: "cost/supplier/supplier-register/index",
          path: "supplier/supplier-register",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 2,
        },
      ],
    },
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 153,
      operDate: "2026-04-23 10:07:32",
      id: 153,
      pid: 9898,
      name: "cost-setting",
      title: "成本基本设置",
      icon: "Document",
      menuType: 1,
      component: "cost-setting",
      path: "cost-setting",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 3,
      children: [
        // {
        //   isDel: false,
        //   createId: 1,
        //   createDate: "2025-12-24 10:02:05",
        //   operId: 1,
        //   operDate: "2025-12-24 10:02:05",
        //   id: 16112,
        //   pid: 153,
        //   name: "project-cost",
        //   title: "项目成本业态",
        //   icon: "Edit",
        //   menuType: 1,
        //   component: "cost/cost-setting/project-cost/index",
        //   path: "cost/project-cost",
        //   isKeepAlive: true,
        //   isControl: true,
        //   isVisible: true,
        //   sort: 1,
        // },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161112,
          pid: 153,
          name: "goal-cost",
          title: "目标成本",
          icon: "Edit",
          menuType: 1,
          component: "cost/cost-setting/goal-cost/index",
          path: "cost/goal-cost",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 2,
        },
      ],
    },
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 153,
      operDate: "2026-04-23 10:07:32",
      id: 154,
      pid: 9898,
      name: "bidding",
      title: "招标管理",
      icon: "Document",
      menuType: 1,
      component: "bidding",
      path: "bidding",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 4,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 1611445,
          pid: 154,
          name: "bidding-demand",
          title: "招标需求",
          icon: "Edit",
          menuType: 1,
          component: "cost/bidding/bidding-demand/index",
          path: "bidding/bidding-demand",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 1,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 16112,
          pid: 154,
          name: "tender-matter",
          title: "招标事项",
          icon: "Edit",
          menuType: 1,
          component: "cost/bidding/tender-matter/index",
          path: "bidding/tender-matter",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 2,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 16113,
          pid: 154,
          name: "bidding-detail",
          title: "招标详情",
          icon: "Edit",
          menuType: 1,
          component: "cost/bidding/tender-matter/bidding-detail",
          path: "bidding/bidding-detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 3,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161144,
          pid: 154,
          name: "tender-plan-add",
          title: "新增招标计划",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/tender-plan/tender-plan-form",
          path: "bidding/tender-plan/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 4,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161145,
          pid: 154,
          name: "tender-plan-edit",
          title: "编辑招标计划",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/tender-plan/tender-plan-form",
          path: "bidding/tender-plan/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 5,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161146,
          pid: 154,
          name: "tender-plan-detail",
          title: "招标计划详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/tender-plan/tender-plan-form",
          path: "bidding/tender-plan/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 6,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161147,
          pid: 154,
          name: "reference-price-add",
          title: "新增招标参考价",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/reference-price/reference-price-form",
          path: "bidding/reference-price/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 6,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161148,
          pid: 154,
          name: "reference-price-edit",
          title: "编辑招标参考价",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/reference-price/reference-price-form",
          path: "bidding/reference-price/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 7,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161149,
          pid: 154,
          name: "reference-price-detail",
          title: "招标参考价详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/reference-price/reference-price-form",
          path: "bidding/reference-price/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 8,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161150,
          pid: 154,
          name: "award-approval-add",
          title: "新增定标审批",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/award-approval/award-approval-form",
          path: "bidding/award-approval/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 9,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161151,
          pid: 154,
          name: "award-approval-edit",
          title: "编辑定标审批",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/award-approval/award-approval-form",
          path: "bidding/award-approval/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 10,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161152,
          pid: 154,
          name: "award-approval-detail",
          title: "定标审批详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/award-approval/award-approval-form",
          path: "bidding/award-approval/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 11,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161153,
          pid: 154,
          name: "bid-bond-pay-add",
          title: "新增保证金缴纳",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-pay/bond-pay-form",
          path: "bidding/bid-bond-pay/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 12,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161154,
          pid: 154,
          name: "bid-bond-pay-edit",
          title: "编辑保证金缴纳",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-pay/bond-pay-form",
          path: "bidding/bid-bond-pay/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 13,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161155,
          pid: 154,
          name: "bid-bond-pay-detail",
          title: "保证金缴纳详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-pay/bond-pay-form",
          path: "bidding/bid-bond-pay/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 14,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161156,
          pid: 154,
          name: "bid-bond-refund-add",
          title: "新增保证金退还",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-refund/bond-refund-form",
          path: "bidding/bid-bond-refund/add",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 15,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161157,
          pid: 154,
          name: "bid-bond-refund-edit",
          title: "编辑保证金退还",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-refund/bond-refund-form",
          path: "bidding/bid-bond-refund/edit",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 16,
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 161158,
          pid: 154,
          name: "bid-bond-refund-detail",
          title: "保证金退还详情",
          icon: "Edit",
          menuType: 1,
          component:
            "cost/bidding/tender-matter/components/bid-bond-refund/bond-refund-form",
          path: "bidding/bid-bond-refund/detail",
          isKeepAlive: true,
          isControl: true,
          isVisible: false,
          sort: 17,
        },
      ],
    },
    {
      isDel: false,
      createId: 1,
      createDate: "2025-12-24 10:00:17",
      operId: 153,
      operDate: "2026-04-23 10:07:32",
      id: 1541,
      pid: 9899,
      name: "contract-manage",
      title: "合同管理",
      icon: "Document",
      menuType: 1,
      component: "contract-manage",
      path: "contract-manage",
      isKeepAlive: false,
      isMultiOpen: false,
      isControl: true,
      isVisible: true,
      sort: 5,
      children: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-24 10:02:05",
          operId: 1,
          operDate: "2025-12-24 10:02:05",
          id: 13541,
          pid: 1540,
          name: "contract-ledger",
          title: "合同台账",
          icon: "Edit",
          menuType: 1,
          component: "cost/contract-manage/contract-ledger/index",
          path: "contract-manage/contract-ledger",
          isKeepAlive: true,
          isControl: true,
          isVisible: true,
          sort: 1,
        },
      ],
    },
  ],
};
