import { http } from "@/axios/service";

interface UserInfo {
  id: number;
  name: string;
  email: string;
}

export const userApi = {
  // 登录
  login: (data: FormData) => {
    return http.post("/auth/login", data);
  },
  // 获取用户信息
  getUserInfo: () => {
    return http.get<UserInfo>("/user/info");
  },
  // 退出登录
  logout: (data: any) => {
    return http.post(`/auth/logout`,data);
  },
  // 获取当前用户的菜单数据
  getUserMenuPowerList: async () => {
    // return http.post("/auth/getUserMenuPowerList");
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return [
      {
        id: 1,
        pid: 0,
        name: "dashboard",
        title: "工作台",
        icon: "DataBoard",
        menuType: 0,
        component: "",
        path: "",
        isKeepAlive: false,
        isMuitlOpen: false,
        isControl: true,
        isVisible: true,
        sort: 1,
        isDel: false,
        createId: 0,
        children: [
          {
            id: 2,
            pid: 1,
            name: "home",
            title: "首页",
            icon: "HomeFilled",
            menuType: 1,
            component: "home/index",
            path: "home",
            isKeepAlive: true,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 1,
            isDel: false,
            createId: 0,
          },
        ],
      },
      {
        id: 3,
        pid: 0,
        name: "dashboard-analysis",
        title: "大屏分析",
        icon: "Monitor",
        menuType: 0,
        component: "",
        path: "",
        isKeepAlive: false,
        isMuitlOpen: false,
        isControl: true,
        isVisible: true,
        sort: 2,
        isDel: false,
        createId: 0,
        children: [
          {
            id: 4,
            pid: 3,
            name: "sales-analysis",
            title: "销售分析",
            icon: "Monitor",
            menuType: 1,
            component: "",
            path: "sales-analysis",
            isKeepAlive: false,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 1,
            isDel: false,
            createId: 0,
            children: [
              {
                id: 5,
                pid: 4,
                name: "large-screen",
                title: "销售战略大屏",
                icon: "Monitor",
                menuType: 1,
                component: "sales-analysis/large-screen",
                path: "sales-analysis/large-screen",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 1,
                isDel: false,
                createId: 0,
                children: [
                  {
                    id: 6,
                    pid: 5,
                    name: "menuList:add",
                    title: "新增",
                    menuType: 2,
                    component: "",
                    path: "",
                    isKeepAlive: false,
                    isMuitlOpen: false,
                    isControl: true,
                    isVisible: true,
                    sort: 1,
                    isDel: false,
                    createId: 0,
                  },
                  {
                    id: 7,
                    pid: 5,
                    name: "menuList:edit",
                    title: "修改",
                    menuType: 2,
                    component: "",
                    path: "",
                    isKeepAlive: false,
                    isMuitlOpen: false,
                    isControl: true,
                    isVisible: true,
                    sort: 2,
                    isDel: false,
                    createId: 0,
                  },
                  {
                    id: 8,
                    pid: 5,
                    name: "menuList:del",
                    title: "删除",
                    menuType: 2,
                    component: "",
                    path: "",
                    isKeepAlive: false,
                    isMuitlOpen: false,
                    isControl: true,
                    isVisible: true,
                    sort: 3,
                    isDel: false,
                    createId: 0,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 9,
        pid: 0,
        name: "system",
        title: "系统管理",
        icon: "Setting",
        menuType: 0,
        component: "",
        path: "",
        isKeepAlive: false,
        isMuitlOpen: false,
        isControl: true,
        isVisible: true,
        sort: 3,
        isDel: false,
        createId: 0,
        children: [
          {
            id: 10,
            pid: 9,
            name: "role",
            title: "角色管理",
            icon: "Document",
            menuType: 1,
            component: "system/role/index",
            path: "system/role",
            isKeepAlive: true,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 1,
            isDel: false,
            createId: 0,
          },
          {
            id: 11,
            pid: 9,
            name: "menu",
            title: "菜单管理",
            icon: "Document",
            menuType: 1,
            component: "system/menu/index",
            path: "system/menu",
            isKeepAlive: false,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 2,
            isDel: false,
            createId: 0,
          },
          {
            id: 12,
            pid: 9,
            name: "user",
            title: "个人中心",
            icon: "Document",
            menuType: 1,
            component: "system/user/index",
            path: "system/user",
            isKeepAlive: false,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 3,
            isDel: false,
            createId: 0,
          },
        ],
      },
    ];
  },
};
