import { http } from "@/axios/service";

interface UserInfo {
  id: number;
  name: string;
  email: string;
}

export const userApi = {
  // 登录
  login: (data: FormData) => {
    return http.post("/auth/login", data);
  },
  test: () => {
    return http.get("/test/test1");
  },
  // 获取用户信息
  getUserInfo: () => {
    return http.get<UserInfo>("/user/info");
  },
  // 退出登录
  logout: (data: any) => {
    return http.post(`/auth/logout`, data);
  },
  // 获取当前用户的菜单数据
  getUserMenuPowerList: async () => {
    // return http.post("/auth/getUserMenuPowerList");
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return [
      {
        id: 1,
        pid: 0,
        name: "dashboard",
        title: "工作台",
        icon: "DataBoard", // 图标
        menuType: 0, // 0:模块   1:菜单   2:按钮
        component: "", // 组件路径
        path: "", // 路由路径
        isKeepAlive: false, // 是否缓存
        isMuitlOpen: false, // 是否多开
        isControl: true,
        isVisible: true, // 是否可见
        sort: 1,
        isDel: false,
        createId: 0,
        children: [
          {
            id: 2,
            pid: 1,
            name: "home",
            title: "首页",
            icon: "HomeFilled",
            menuType: 1,
            component: "home/index",
            path: "home",
            isKeepAlive: true,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 1,
            isDel: false,
            createId: 0,
          },
        ],
      },
      {
        id: 3,
        pid: 0,
        name: "dashboard-analysis",
        title: "大屏分析",
        icon: "Monitor",
        menuType: 0,
        component: "",
        path: "",
        isKeepAlive: false,
        isMuitlOpen: false,
        isControl: true,
        isVisible: true,
        sort: 2,
        isDel: false,
        createId: 0,
        children: [
          {
            id: 5,
            pid: 4,
            name: "large-screen",
            title: "销售战略大屏",
            icon: "Monitor",
            menuType: 1,
            component: "sales-analysis/large-screen",
            path: "sales-analysis/large-screen",
            isKeepAlive: true,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 1,
            isDel: false,
            createId: 0,
          },
          {
            id: 4,
            pid: 3,
            name: "asset-management",
            title: "资产管理",
            icon: "Monitor",
            menuType: 1,
            component: "",
            path: "asset-management",
            isKeepAlive: false,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 2,
            isDel: false,
            createId: 0,
            children: [
              {
                id: 5,
                pid: 4,
                name: "room-ledger",
                title: "房间台账表",
                icon: "Monitor",
                menuType: 1,
                component: "asset-management/room-ledger",
                path: "asset-management/room-ledger",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 1,
                isDel: false,
                createId: 0,
              },
              {
                id: 55,
                pid: 4,
                name: "inventory-statistics",
                title: "库存统计表",
                icon: "Monitor",
                menuType: 1,
                component: "asset-management/inventory-statistics",
                path: "asset-management/inventory-statistics",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 2,
                isDel: false,
                createId: 0,
              },
              {
                id: 555,
                pid: 4,
                name: "inventory-detail",
                title: "库存明细表",
                icon: "Monitor",
                menuType: 1,
                component: "asset-management/inventory-detail",
                path: "asset-management/inventory-detail",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 3,
                isDel: false,
                createId: 0,
              },
            ],
          },
          {
            id: 41,
            pid: 3,
            name: "channel-analysis",
            title: "渠道及转化分析",
            icon: "Monitor",
            menuType: 1,
            component: "",
            path: "channel-analysis",
            isKeepAlive: false,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 3,
            isDel: false,
            createId: 0,
            children: [
              {
                id: 411,
                pid: 4,
                name: "visiting-statistics",
                title: "来访统计",
                icon: "Monitor",
                menuType: 1,
                component: "channel-analysis/visiting-statistics",
                path: "channel-analysis/visiting-statistics",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 1,
                isDel: false,
                createId: 0,
              },
              {
                id: 412,
                pid: 4,
                name: "visiting-channel",
                title: "来访渠道分析",
                icon: "Monitor",
                menuType: 1,
                component: "channel-analysis/visiting-channel",
                path: "channel-analysis/visiting-channel",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 2,
                isDel: false,
                createId: 0,
              },
              {
                id: 413,
                pid: 4,
                name: "deal-channel",
                title: "成交渠道分析",
                icon: "Monitor",
                menuType: 1,
                component: "channel-analysis/deal-channel",
                path: "channel-analysis/deal-channel",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 3,
                isDel: false,
                createId: 0,
              },
              {
                id: 414,
                pid: 4,
                name: "conversion-rate",
                title: "转化率统计",
                icon: "Monitor",
                menuType: 1,
                component: "channel-analysis/conversion-rate",
                path: "channel-analysis/conversion-rate",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 3,
                isDel: false,
                createId: 0,
              },
            ],
          },
          {
            id: 51,
            pid: 3,
            name: "performance-analysis",
            title: "业绩分析",
            icon: "Monitor",
            menuType: 1,
            component: "",
            path: "performance-analysis",
            isKeepAlive: false,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 4,
            isDel: false,
            createId: 0,
            children: [
              {
                id: 511,
                pid: 4,
                name: "annual-report",
                title: "销售年报表",
                icon: "Monitor",
                menuType: 1,
                component: "performance-analysis/annual-report",
                path: "performance-analysis/annual-report",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 1,
                isDel: false,
                createId: 0,
              },
              {
                id: 512,
                pid: 4,
                name: "daily-report",
                title: "销售日报表",
                icon: "Monitor",
                menuType: 1,
                component: "performance-analysis/daily-report",
                path: "performance-analysis/daily-report",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 2,
                isDel: false,
                createId: 0,
              },
              {
                id: 513,
                pid: 4,
                name: "subscription-statistics",
                title: "认购达成统计",
                icon: "Monitor",
                menuType: 1,
                component: "performance-analysis/subscription-statistics",
                path: "performance-analysis/subscription-statistics",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 3,
                isDel: false,
                createId: 0,
              },
              {
                id: 514,
                pid: 4,
                name: "agent-ranking",
                title: "置业顾问排名",
                icon: "Monitor",
                menuType: 1,
                component: "performance-analysis/agent-ranking",
                path: "performance-analysis/agent-ranking",
                isKeepAlive: true,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 3,
                isDel: false,
                createId: 0,
              },
            ],
          },
        ],
      },
      {
        id: 9,
        pid: 0,
        name: "system",
        title: "系统管理",
        icon: "Setting",
        menuType: 0,
        component: "",
        path: "",
        isKeepAlive: false,
        isMuitlOpen: false,
        isControl: true,
        isVisible: true,
        sort: 3,
        isDel: false,
        createId: 0,
        children: [
          {
            id: 10,
            pid: 9,
            name: "role",
            title: "角色管理",
            icon: "Document",
            menuType: 1,
            component: "system/role/index",
            path: "system/role",
            isKeepAlive: true,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 1,
            isDel: false,
            createId: 0,
          },
          {
            id: 11,
            pid: 9,
            name: "menu",
            title: "菜单管理",
            icon: "Document",
            menuType: 1,
            component: "system/menu/index",
            path: "system/menu",
            isKeepAlive: false,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 2,
            isDel: false,
            createId: 0,
            children: [
              {
                id: 6,
                pid: 5,
                name: "menuList:add",
                title: "新增",
                menuType: 2,
                component: "",
                path: "",
                isKeepAlive: false,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 1,
                isDel: false,
                createId: 0,
              },
              {
                id: 7,
                pid: 5,
                name: "menuList:edit",
                title: "修改",
                menuType: 2,
                component: "",
                path: "",
                isKeepAlive: false,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 2,
                isDel: false,
                createId: 0,
              },
              {
                id: 8,
                pid: 5,
                name: "menuList:del",
                title: "删除",
                menuType: 2,
                component: "",
                path: "",
                isKeepAlive: false,
                isMuitlOpen: false,
                isControl: true,
                isVisible: true,
                sort: 3,
                isDel: false,
                createId: 0,
              },
            ],
          },
          {
            id: 12,
            pid: 9,
            name: "user",
            title: "个人中心",
            icon: "Document",
            menuType: 1,
            component: "system/user/index",
            path: "system/user",
            isKeepAlive: false,
            isMuitlOpen: false,
            isControl: true,
            isVisible: true,
            sort: 3,
            isDel: false,
            createId: 0,
          },
        ],
      },
    ];
  },
};
