import { http } from "@/axios/service";

interface UserInfo {
  id: number;
  name: string;
  email: string;
}

export const userApi = {
  // 登录
  login: (data: FormData) => {
    return http.post("/auth/login", data);
  },
  // 测试接口
  test: () => {
    return http.get("/test/test1");
  },
  // 获取用户信息
  getUserInfo: () => {
    return http.get<UserInfo>("/user/info");
  },
  // 退出登录
  logout: () => {
    return http.post(`/auth/logout`);
  },
  // 获取二维码
  createQrCode: (data: any) => {
    return http.post(`/callback/createQrCode`, data);
  },
  // 获取扫码后的token
  getTokenForAutoLogin: (data: any) => {
    return http.post(`/callback/getTokenForAutoLogin`, data);
  },
  // 一键登录
  getAuthRedirectUrl: (data: any) => {
    return http.post(`/callback/getAuthRedirectUrl`, data);
  },
  // 一键登录（测试）
  getAuthRedirectUrlTest: (data: any) => {
    return http.post(`/callback/getAuthRedirectUrlTest`, data);
  },
  // 获取用户信息
  getEmpInfo: () => {
    return http.post(`/emp/getEmpInfo`);
  },
  // 修改密码
  resetPassword: (data: any) => {
    return http.post(`/auth/resetPassword`, data);
  },
  // 获取当前用户的菜单数据
  getUserMenuPowerList: async () => {
    // return http.post("/auth/getUserMenuPowerList");
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return {
      code: 200,
      message: "success",
      data: [
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-23 16:41:38",
          id: 1,
          pid: 0,
          name: "dashboard",
          title: "工作台",
          icon: "DataBoard",
          menuType: 0,
          component: "",
          path: "",
          isKeepAlive: false,
          isMultiOpen: false,
          isControl: false,
          isVisible: true,
          sort: 1,
          children: [
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-23 16:41:38",
              operId: 1,
              operDate: "2025-12-31 09:37:38",
              id: 2,
              pid: 1,
              name: "home",
              title: "首页",
              icon: "HomeFilled",
              menuType: 1,
              component: "home/index",
              path: "home",
              isKeepAlive: false,
              isMultiOpen: false,
              isControl: false,
              isVisible: true,
              sort: 1,
            },
          ],
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-23 16:41:38",
          operId: 1,
          operDate: "2025-12-23 16:41:38",
          id: 13,
          pid: 0,
          name: "dashboard-analysis",
          title: "大屏分析",
          icon: "Monitor",
          menuType: 0,
          component: "",
          path: "",
          isKeepAlive: false,
          isControl: true,
          isVisible: true,
          sort: 2,
          children: [
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-23 16:41:38",
              operId: 1,
              operDate: "2025-12-30 19:01:55",
              id: 5,
              pid: 13,
              name: "large-screen",
              title: "销售战略大屏",
              icon: "DataBoard",
              menuType: 1,
              component: "sales-analysis/large-screen",
              path: "sales-analysis/large-screen",
              isKeepAlive: true,
              isMultiOpen: false,
              isControl: true,
              isVisible: true,
              sort: 1,
            },
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-24 10:00:17",
              operId: 15,
              operDate: "2026-04-23 10:07:32",
              id: 15,
              pid: 13,
              name: "asset-management",
              title: "资产管理",
              icon: "Document",
              menuType: 1,
              component: "asset-management",
              path: "asset-management",
              isKeepAlive: false,
              isMultiOpen: false,
              isControl: true,
              isVisible: true,
              sort: 2,
              children: [
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-24 10:02:05",
                  operId: 1,
                  operDate: "2025-12-24 10:02:05",
                  id: 16,
                  pid: 15,
                  name: "room-ledger",
                  title: "房间台账表",
                  icon: "Edit",
                  menuType: 1,
                  component: "asset-management/room-ledger",
                  path: "asset-management/room-ledger",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 1,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:20:36",
                      operId: 1,
                      operDate: "2025-12-30 10:42:40",
                      id: 43,
                      pid: 16,
                      name: "room-ledger:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-30 10:38:20",
                      operId: 1,
                      operDate: "2025-12-30 10:38:20",
                      id: 67,
                      pid: 16,
                      name: "room-ledger:showTel",
                      title: "显示号码",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 2,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-24 10:03:40",
                  operId: 1,
                  operDate: "2025-12-24 10:03:40",
                  id: 17,
                  pid: 15,
                  name: "inventory-statistics",
                  title: "库存统计表",
                  icon: "Document",
                  menuType: 1,
                  component: "asset-management/inventory-statistics",
                  path: "asset-management/inventory-statistics",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 2,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:23:56",
                      operId: 1,
                      operDate: "2025-12-30 10:42:45",
                      id: 44,
                      pid: 17,
                      name: "inventory-statistics:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-24 10:04:40",
                  operId: 1,
                  operDate: "2025-12-24 10:04:40",
                  id: 18,
                  pid: 15,
                  name: "inventory-detail",
                  title: "库存明细表",
                  icon: "Files",
                  menuType: 1,
                  component: "asset-management/inventory-detail",
                  path: "asset-management/inventory-detail",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 3,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:25:25",
                      operId: 1,
                      operDate: "2025-12-30 10:42:53",
                      id: 45,
                      pid: 18,
                      name: "inventory-detail:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 15,
                  createDate: "2026-03-23 17:07:03",
                  operId: 15,
                  operDate: "2026-03-23 17:07:03",
                  id: 94,
                  pid: 15,
                  name: "output-statistics",
                  title: "产值统计表",
                  icon: "Document",
                  menuType: 1,
                  component: "asset-management/output-statistics",
                  path: "asset-management/output-statistics",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 4,
                  children: [
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-03-25 09:28:26",
                      operId: 15,
                      operDate: "2026-03-25 09:28:26",
                      id: 95,
                      pid: 94,
                      name: "output-statistics:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
              ],
            },
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-29 16:50:37",
              operId: 11,
              operDate: "2025-12-31 14:40:36",
              id: 24,
              pid: 13,
              name: "performance-analysis",
              title: "业绩分析",
              icon: "TrendCharts",
              menuType: 1,
              component: "performance-analysis",
              path: "performance-analysis",
              isKeepAlive: false,
              isMultiOpen: false,
              isControl: true,
              isVisible: true,
              sort: 3,
              children: [
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:51:22",
                  operId: 1,
                  operDate: "2025-12-29 16:51:22",
                  id: 25,
                  pid: 24,
                  name: "annual-report",
                  title: "销售年报表",
                  icon: "Monitor",
                  menuType: 1,
                  component: "performance-analysis/annual-report",
                  path: "performance-analysis/annual-report",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 1,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:43:07",
                      operId: 1,
                      operDate: "2025-12-30 10:43:59",
                      id: 50,
                      pid: 25,
                      name: "annual-report:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 15,
                  createDate: "2026-01-13 17:14:55",
                  operId: 11,
                  operDate: "2026-01-16 19:42:31",
                  id: 90,
                  pid: 24,
                  name: "tree-annual-report",
                  title: "销售年报表(业绩)",
                  icon: "Document",
                  menuType: 1,
                  component: "performance-analysis/tree-annual-report",
                  path: "performance-analysis/tree-annual-report",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 2,
                  children: [
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-13 17:15:20",
                      operId: 15,
                      operDate: "2026-01-13 17:15:20",
                      id: 91,
                      pid: 90,
                      name: "tree-annual-report:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:51:50",
                  operId: 15,
                  operDate: "2026-01-13 17:13:02",
                  id: 26,
                  pid: 24,
                  name: "daily-report",
                  title: "销售日报表",
                  icon: "",
                  menuType: 1,
                  component: "performance-analysis/daily-report",
                  path: "performance-analysis/daily-report",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 3,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:44:06",
                      operId: 1,
                      operDate: "2025-12-30 10:44:15",
                      id: 51,
                      pid: 26,
                      name: "daily-report:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 15,
                  createDate: "2026-01-13 17:16:19",
                  operId: 11,
                  operDate: "2026-01-16 19:42:40",
                  id: 92,
                  pid: 24,
                  name: "tree-daily-report",
                  title: "销售日报表(业绩)",
                  icon: "Document",
                  menuType: 1,
                  component: "performance-analysis/tree-daily-report",
                  path: "performance-analysis/tree-daily-report",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 4,
                  children: [
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-13 17:16:42",
                      operId: 15,
                      operDate: "2026-01-13 17:16:42",
                      id: 93,
                      pid: 92,
                      name: "tree-daily-report:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:53:52",
                  operId: 15,
                  operDate: "2026-01-13 17:12:55",
                  id: 27,
                  pid: 24,
                  name: "sub-detail",
                  title: "认购业绩明细",
                  icon: "",
                  menuType: 1,
                  component: "performance-analysis/sub-detail",
                  path: "performance-analysis/sub-detail",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 5,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:44:33",
                      operId: 1,
                      operDate: "2025-12-30 10:44:28",
                      id: 52,
                      pid: 27,
                      name: "sub-detail:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-04 15:57:41",
                      operId: 15,
                      operDate: "2026-01-04 15:58:05",
                      id: 79,
                      pid: 27,
                      name: "sub-detail:showTel",
                      title: "显示电话",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 2,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:54:25",
                  operId: 15,
                  operDate: "2026-01-13 17:12:50",
                  id: 28,
                  pid: 24,
                  name: "contract-detail",
                  title: "签约业绩明细",
                  icon: "",
                  menuType: 1,
                  component: "performance-analysis/contract-detail",
                  path: "performance-analysis/contract-detail",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 6,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:45:08",
                      operId: 1,
                      operDate: "2025-12-30 10:44:40",
                      id: 53,
                      pid: 28,
                      name: "contract-detail:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-04 15:58:35",
                      operId: 15,
                      operDate: "2026-01-04 15:58:35",
                      id: 80,
                      pid: 28,
                      name: "contract-detail:showTel",
                      title: "显示电话",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 2,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:55:00",
                  operId: 15,
                  operDate: "2026-01-13 17:12:44",
                  id: 29,
                  pid: 24,
                  name: "collection-detail",
                  title: "回款业绩明细",
                  icon: "Setting",
                  menuType: 1,
                  component: "performance-analysis/collection-detail",
                  path: "performance-analysis/collection-detail",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 7,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:45:38",
                      operId: 1,
                      operDate: "2025-12-30 10:44:56",
                      id: 54,
                      pid: 29,
                      name: "collection-detail:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-04 15:59:07",
                      operId: 15,
                      operDate: "2026-01-04 15:59:07",
                      id: 81,
                      pid: 29,
                      name: "collection-detail:showTel",
                      title: "显示电话",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 2,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:55:28",
                  operId: 15,
                  operDate: "2026-01-13 17:12:39",
                  id: 30,
                  pid: 24,
                  name: "subscription-statistics",
                  title: "认购达成统计",
                  icon: "Setting",
                  menuType: 1,
                  component: "performance-analysis/subscription-statistics",
                  path: "performance-analysis/subscription-statistics",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 8,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:46:27",
                      operId: 1,
                      operDate: "2025-12-30 10:45:08",
                      id: 55,
                      pid: 30,
                      name: "subscription-statistics:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:55:57",
                  operId: 15,
                  operDate: "2026-01-13 17:12:34",
                  id: 31,
                  pid: 24,
                  name: "agent-ranking",
                  title: "置业顾问排名",
                  icon: "Setting",
                  menuType: 1,
                  component: "performance-analysis/agent-ranking",
                  path: "performance-analysis/agent-ranking",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 9,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:47:19",
                      operId: 1,
                      operDate: "2025-12-30 10:45:23",
                      id: 56,
                      pid: 31,
                      name: "agent-ranking:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
              ],
            },
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-24 10:06:36",
              operId: 11,
              operDate: "2025-12-31 14:40:30",
              id: 19,
              pid: 13,
              name: "channel-analysis",
              title: "渠道及转化",
              icon: "Coin",
              menuType: 1,
              component: "channel-analysis",
              path: "channel-analysis",
              isKeepAlive: false,
              isMultiOpen: false,
              isControl: true,
              isVisible: true,
              sort: 4,
              children: [
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-24 10:07:13",
                  operId: 1,
                  operDate: "2025-12-24 10:07:13",
                  id: 20,
                  pid: 19,
                  name: "visiting-statistics",
                  title: "来访统计",
                  icon: "Setting",
                  menuType: 1,
                  component: "channel-analysis/visiting-statistics",
                  path: "channel-analysis/visiting-statistics",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 1,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:26:55",
                      operId: 1,
                      operDate: "2025-12-30 10:42:59",
                      id: 46,
                      pid: 20,
                      name: "visiting-statistics:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:48:23",
                  operId: 1,
                  operDate: "2025-12-29 16:48:23",
                  id: 21,
                  pid: 19,
                  name: "visiting-channel",
                  title: "来访渠道分析",
                  icon: "Setting",
                  menuType: 1,
                  component: "channel-analysis/visiting-channel",
                  path: "channel-analysis/visiting-channel",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 2,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:36:38",
                      operId: 1,
                      operDate: "2025-12-30 10:43:05",
                      id: 47,
                      pid: 21,
                      name: "visiting-channel:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:49:18",
                  operId: 1,
                  operDate: "2025-12-29 16:49:18",
                  id: 22,
                  pid: 19,
                  name: "deal-channel",
                  title: "认购渠道分析",
                  icon: "Setting",
                  menuType: 1,
                  component: "channel-analysis/deal-channel",
                  path: "channel-analysis/deal-channel",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 3,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:38:56",
                      operId: 1,
                      operDate: "2025-12-30 10:43:25",
                      id: 48,
                      pid: 22,
                      name: "deal-channel:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:49:53",
                  operId: 1,
                  operDate: "2025-12-29 16:49:53",
                  id: 23,
                  pid: 19,
                  name: "conversion-rate",
                  title: "转化率统计",
                  icon: "Setting",
                  menuType: 1,
                  component: "channel-analysis/conversion-rate",
                  path: "channel-analysis/conversion-rate",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 4,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:39:42",
                      operId: 1,
                      operDate: "2025-12-30 10:43:43",
                      id: 49,
                      pid: 23,
                      name: "conversion-rate:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 15,
                  createDate: "2026-04-14 11:19:59",
                  operId: 15,
                  operDate: "2026-04-14 11:19:59",
                  id: 96,
                  pid: 19,
                  name: "visiting-record",
                  title: "来访记录",
                  icon: "DataBoard",
                  menuType: 1,
                  component: "channel-analysis/visiting-record",
                  path: "channel-analysis/visiting-record",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 5,
                },
              ],
            },
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-29 16:57:29",
              operId: 11,
              operDate: "2025-12-31 14:40:57",
              id: 32,
              pid: 13,
              name: "risk-analysis",
              title: "指标分析",
              icon: "PieChart",
              menuType: 1,
              component: "risk-analysis",
              path: "risk-analysis",
              isKeepAlive: false,
              isMultiOpen: false,
              isControl: true,
              isVisible: true,
              sort: 5,
              children: [
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:58:02",
                  operId: 1,
                  operDate: "2025-12-29 16:58:02",
                  id: 33,
                  pid: 32,
                  name: "conversion-stats",
                  title: "认购转签约统计",
                  icon: "",
                  menuType: 1,
                  component: "risk-analysis/conversion-stats",
                  path: "risk-analysis/conversion-stats",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 1,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:47:48",
                      operId: 1,
                      operDate: "2025-12-30 10:45:52",
                      id: 57,
                      pid: 33,
                      name: "conversion-stats:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:58:31",
                  operId: 1,
                  operDate: "2025-12-29 16:58:31",
                  id: 34,
                  pid: 32,
                  name: "conversion-detail",
                  title: "认购转签约明细",
                  icon: "Setting",
                  menuType: 1,
                  component: "risk-analysis/conversion-detail",
                  path: "risk-analysis/conversion-detail",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 2,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:48:18",
                      operId: 1,
                      operDate: "2025-12-30 10:47:09",
                      id: 58,
                      pid: 34,
                      name: "conversion-detail:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-04 15:59:46",
                      operId: 15,
                      operDate: "2026-01-04 15:59:46",
                      id: 82,
                      pid: 34,
                      name: "conversion-detail:showTel",
                      title: "显示电话",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 2,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:59:11",
                  operId: 1,
                  operDate: "2025-12-29 16:59:11",
                  id: 35,
                  pid: 32,
                  name: "pending-stats",
                  title: "认购未签约统计",
                  icon: "Monitor",
                  menuType: 1,
                  component: "risk-analysis/pending-stats",
                  path: "risk-analysis/pending-stats",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 3,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:48:46",
                      operId: 1,
                      operDate: "2025-12-30 10:47:20",
                      id: 59,
                      pid: 35,
                      name: "pending-stats:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 16:59:38",
                  operId: 1,
                  operDate: "2025-12-29 16:59:38",
                  id: 36,
                  pid: 32,
                  name: "pending-detail",
                  title: "认购未签约明细",
                  icon: "",
                  menuType: 1,
                  component: "risk-analysis/pending-detail",
                  path: "risk-analysis/pending-detail",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 4,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:49:14",
                      operId: 1,
                      operDate: "2025-12-30 10:47:37",
                      id: 60,
                      pid: 36,
                      name: "pending-detail:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-04 16:00:13",
                      operId: 15,
                      operDate: "2026-01-04 16:00:13",
                      id: 83,
                      pid: 36,
                      name: "pending-detail:showTel",
                      title: "显示电话",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 2,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 17:00:22",
                  operId: 1,
                  operDate: "2025-12-29 17:00:22",
                  id: 37,
                  pid: 32,
                  name: "premium-stats",
                  title: "溢价统计表",
                  icon: "",
                  menuType: 1,
                  component: "risk-analysis/premium-stats",
                  path: "risk-analysis/premium-stats",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 5,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:50:49",
                      operId: 1,
                      operDate: "2025-12-30 10:47:50",
                      id: 61,
                      pid: 37,
                      name: "premium-stats:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 17:00:50",
                  operId: 1,
                  operDate: "2025-12-29 17:00:50",
                  id: 38,
                  pid: 32,
                  name: "premium-detail",
                  title: "溢价明细表",
                  icon: "",
                  menuType: 1,
                  component: "risk-analysis/premium-detail",
                  path: "risk-analysis/premium-detail",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 6,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 17:56:36",
                      operId: 2,
                      operDate: "2025-12-30 11:24:59",
                      id: 62,
                      pid: 38,
                      name: "premium-detail:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-04 16:00:35",
                      operId: 15,
                      operDate: "2026-01-04 16:00:35",
                      id: 84,
                      pid: 38,
                      name: "premium-detail:showTel",
                      title: "显示电话",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 2,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 17:01:21",
                  operId: 1,
                  operDate: "2025-12-29 17:01:21",
                  id: 39,
                  pid: 32,
                  name: "receivables",
                  title: "应收统计表",
                  icon: "",
                  menuType: 1,
                  component: "risk-analysis/receivables",
                  path: "risk-analysis/receivables",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 7,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 18:00:00",
                      operId: 2,
                      operDate: "2025-12-30 11:25:24",
                      id: 63,
                      pid: 39,
                      name: "receivables:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 17:01:48",
                  operId: 15,
                  operDate: "2026-01-05 10:02:21",
                  id: 40,
                  pid: 32,
                  name: "receivable-detail",
                  title: "应收明细表",
                  icon: "",
                  menuType: 1,
                  component: "risk-analysis/receivable-detail",
                  path: "risk-analysis/receivable-detail",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 8,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 18:00:36",
                      operId: 1,
                      operDate: "2025-12-30 10:49:01",
                      id: 64,
                      pid: 40,
                      name: "receivable-detail:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-04 16:01:05",
                      operId: 15,
                      operDate: "2026-01-04 16:01:05",
                      id: 85,
                      pid: 40,
                      name: "receivable-detail:showTel",
                      title: "显示电话",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 2,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 15,
                  createDate: "2026-01-05 09:15:00",
                  operId: 15,
                  operDate: "2026-01-05 09:15:00",
                  id: 87,
                  pid: 32,
                  name: "aging-detail",
                  title: "应收账龄明细",
                  icon: "Wallet",
                  menuType: 1,
                  component: "risk-analysis/aging-detail",
                  path: "risk-analysis/aging-detail",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 9,
                  children: [
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-05 09:15:35",
                      operId: 15,
                      operDate: "2026-01-05 09:15:35",
                      id: 88,
                      pid: 87,
                      name: "aging-detail:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-05 09:15:57",
                      operId: 15,
                      operDate: "2026-01-05 09:15:57",
                      id: 89,
                      pid: 87,
                      name: "aging-detail:showTel",
                      title: "显示电话",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 2,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 17:02:25",
                  operId: 15,
                  operDate: "2026-01-05 09:13:18",
                  id: 41,
                  pid: 32,
                  name: "forfeiture-stats",
                  title: "退房挞定统计",
                  icon: "Monitor",
                  menuType: 1,
                  component: "risk-analysis/forfeiture-stats",
                  path: "risk-analysis/forfeiture-stats",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 10,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 18:01:03",
                      operId: 1,
                      operDate: "2025-12-30 10:49:15",
                      id: 65,
                      pid: 41,
                      name: "forfeiture-stats:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                  ],
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-29 17:03:11",
                  operId: 15,
                  operDate: "2026-01-05 09:13:24",
                  id: 42,
                  pid: 32,
                  name: "forfeiture-detail",
                  title: "退房挞定明细",
                  icon: "",
                  menuType: 1,
                  component: "risk-analysis/forfeiture-detail",
                  path: "risk-analysis/forfeiture-detail",
                  isKeepAlive: true,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: true,
                  sort: 11,
                  children: [
                    {
                      isDel: false,
                      createId: 1,
                      createDate: "2025-12-29 18:01:29",
                      operId: 1,
                      operDate: "2025-12-30 10:49:27",
                      id: 66,
                      pid: 42,
                      name: "forfeiture-detail:export",
                      title: "导出",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isControl: true,
                      isVisible: false,
                      sort: 1,
                    },
                    {
                      isDel: false,
                      createId: 15,
                      createDate: "2026-01-04 16:01:25",
                      operId: 15,
                      operDate: "2026-01-04 16:01:25",
                      id: 86,
                      pid: 42,
                      name: "forfeiture-detail:showTel",
                      title: "显示电话",
                      icon: "",
                      menuType: 2,
                      component: "",
                      path: "",
                      isKeepAlive: false,
                      isMultiOpen: false,
                      isControl: true,
                      isVisible: false,
                      sort: 2,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-23 16:41:38",
          id: 9,
          pid: 0,
          name: "system",
          title: "系统管理",
          icon: "Setting",
          menuType: 0,
          component: "",
          path: "",
          isKeepAlive: false,
          isMultiOpen: false,
          isControl: true,
          isVisible: true,
          sort: 3,
          children: [
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-23 16:41:38",
              operId: 1,
              operDate: "2025-12-29 19:52:07",
              id: 10,
              pid: 9,
              name: "role",
              title: "角色管理",
              icon: "Wallet",
              menuType: 1,
              component: "system/role/index",
              path: "system/role",
              isKeepAlive: true,
              isMultiOpen: false,
              isControl: true,
              isVisible: true,
              sort: 1,
              children: [
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-23 16:41:38",
                  operId: 2,
                  operDate: "2025-12-30 11:39:50",
                  id: 6,
                  pid: 10,
                  name: "role:add",
                  title: "角色新增",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 1,
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-23 16:41:38",
                  operId: 2,
                  operDate: "2025-12-30 11:40:00",
                  id: 7,
                  pid: 10,
                  name: "role:edit",
                  title: "角色编辑",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 2,
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-23 16:41:38",
                  operId: 2,
                  operDate: "2025-12-30 11:40:09",
                  id: 8,
                  pid: 10,
                  name: "role:del",
                  title: "角色删除",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 3,
                },
                {
                  isDel: false,
                  createId: 2,
                  createDate: "2025-12-30 11:41:30",
                  operId: 2,
                  operDate: "2025-12-30 11:43:05",
                  id: 68,
                  pid: 10,
                  name: "member:add",
                  title: "成员设置新增",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 4,
                },
                {
                  isDel: false,
                  createId: 2,
                  createDate: "2025-12-30 11:41:53",
                  operId: 2,
                  operDate: "2025-12-30 11:43:12",
                  id: 69,
                  pid: 10,
                  name: "member:edit",
                  title: "成员设置编辑",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 5,
                },
                {
                  isDel: false,
                  createId: 2,
                  createDate: "2025-12-30 11:42:09",
                  operId: 2,
                  operDate: "2025-12-30 11:43:18",
                  id: 70,
                  pid: 10,
                  name: "member:del",
                  title: "成员设置删除",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 6,
                },
                {
                  isDel: false,
                  createId: 2,
                  createDate: "2025-12-30 11:49:53",
                  operId: 2,
                  operDate: "2025-12-30 11:50:01",
                  id: 71,
                  pid: 10,
                  name: "menu-permissions:edit",
                  title: "菜单权限编辑",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 7,
                },
                {
                  isDel: false,
                  createId: 2,
                  createDate: "2025-12-30 11:52:15",
                  operId: 2,
                  operDate: "2025-12-30 11:52:21",
                  id: 72,
                  pid: 10,
                  name: "department-permissions:edit",
                  title: "组织权限编辑",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 8,
                },
                {
                  isDel: false,
                  createId: 2,
                  createDate: "2025-12-30 11:52:57",
                  operId: 2,
                  operDate: "2025-12-30 11:52:57",
                  id: 73,
                  pid: 10,
                  name: "project-permissions:edit",
                  title: "项目权限编辑",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 9,
                },
                {
                  isDel: false,
                  createId: 2,
                  createDate: "2025-12-30 11:53:22",
                  operId: 2,
                  operDate: "2025-12-30 11:53:22",
                  id: 74,
                  pid: 10,
                  name: "major-permissions:edit",
                  title: "专业权限编辑",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 10,
                },
                {
                  isDel: false,
                  createId: 2,
                  createDate: "2025-12-30 11:53:54",
                  operId: 2,
                  operDate: "2025-12-30 11:53:54",
                  id: 75,
                  pid: 10,
                  name: "personnel-permissions:add",
                  title: "人员权限新增",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 11,
                },
                {
                  isDel: false,
                  createId: 2,
                  createDate: "2025-12-30 11:54:13",
                  operId: 2,
                  operDate: "2025-12-30 11:54:13",
                  id: 76,
                  pid: 10,
                  name: "personnel-permissions:del",
                  title: "人员权限删除",
                  icon: "",
                  menuType: 2,
                  component: "",
                  path: "",
                  isKeepAlive: false,
                  isMultiOpen: false,
                  isControl: true,
                  isVisible: false,
                  sort: 12,
                },
              ],
            },
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-23 16:45:51",
              operId: 1,
              operDate: "2025-12-29 19:50:30",
              id: 14,
              pid: 9,
              name: "menu",
              title: "菜单管理",
              icon: "Tools",
              menuType: 1,
              component: "system/menu/index",
              path: "system/menu",
              isKeepAlive: false,
              isControl: true,
              isVisible: true,
              sort: 2,
            },
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-31 14:56:40",
              operId: 15,
              operDate: "2025-12-31 15:35:44",
              id: 77,
              pid: 9,
              name: "user",
              title: "个人中心",
              icon: "User",
              menuType: 1,
              component: "system/user/index",
              path: "system/user",
              isKeepAlive: false,
              isMultiOpen: false,
              isControl: false,
              isVisible: true,
              sort: 3,
            },
          ],
        },
        {
          isDel: false,
          createId: 1,
          createDate: "2025-12-23 16:41:38",
          operId: 1,
          operDate: "2025-12-23 16:41:38",
          id: 9898,
          pid: 0,
          name: "cost-management",
          title: "成本管理",
          icon: "Monitor",
          menuType: 0,
          component: "",
          path: "",
          isKeepAlive: false,
          isControl: true,
          isVisible: true,
          sort: 4,
          children: [
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-24 10:00:17",
              operId: 151,
              operDate: "2026-04-23 10:07:32",
              id: 151,
              pid: 9898,
              name: "master-data",
              title: "主数据",
              icon: "Document",
              menuType: 1,
              component: "master-data",
              path: "master-data",
              isKeepAlive: false,
              isMultiOpen: false,
              isControl: true,
              isVisible: true,
              sort: 1,
              children: [
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-24 10:02:05",
                  operId: 1,
                  operDate: "2025-12-24 10:02:05",
                  id: 161,
                  pid: 151,
                  name: "dictionary",
                  title: "数据字典",
                  icon: "Edit",
                  menuType: 1,
                  component: "cost/master-data/dictionary",
                  path: "master-data/dictionary",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 1,
                },
                {
                  isDel: false,
                  createId: 2,
                  createDate: "2025-12-24 10:02:05",
                  operId: 1,
                  operDate: "2025-12-24 10:02:05",
                  id: 162,
                  pid: 151,
                  name: "project-area",
                  title: "项目面积",
                  icon: "Edit",
                  menuType: 1,
                  component: "cost/master-data/project-area/index",
                  path: "master-data/project-area",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 2,
                },
              ],
            },
            {
              isDel: false,
              createId: 1,
              createDate: "2025-12-24 10:00:17",
              operId: 152,
              operDate: "2026-04-23 10:07:32",
              id: 152,
              pid: 9898,
              name: "supplier",
              title: "供应商",
              icon: "Document",
              menuType: 1,
              component: "supplier",
              path: "supplier",
              isKeepAlive: false,
              isMultiOpen: false,
              isControl: true,
              isVisible: true,
              sort: 2,
              children: [
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-24 10:02:05",
                  operId: 1,
                  operDate: "2025-12-24 10:02:05",
                  id: 16111,
                  pid: 152,
                  name: "supplier-ledger",
                  title: "供应商台账",
                  icon: "Edit",
                  menuType: 1,
                  component: "cost/supplier/supplier-ledger",
                  path: "supplier/supplier-ledger",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: true,
                  sort: 1,
                },
                {
                  isDel: false,
                  createId: 1,
                  createDate: "2025-12-24 10:02:05",
                  operId: 1,
                  operDate: "2025-12-24 10:02:05",
                  id: 16222,
                  pid: 152,
                  name: "supplier-register",
                  title: "供应商登记",
                  icon: "Edit",
                  menuType: 1,
                  component: "cost/supplier/supplier-register/index",
                  path: "supplier/supplier-register",
                  isKeepAlive: true,
                  isControl: true,
                  isVisible: false,
                  sort: 2,
                },
              ],
            },
          ],
        },
      ],
    };
  },
};
